Import('env')

headers = []
instances = []
sources = []
aliases = {}

periph = env['PLATFORM_SPEC'].get('periph', {})

def template(n, of, p, deftype=None):
    headers = []
    instances = []
    isources = []
    aliases = {}
    if n in p:
        headers.append(f"{n}.h")
        for name, data in p[n].items():
            subtype = data.get("type", deftype)
            if subtype:
                subtype += "_"
            instances.append({
                'type': f"{n.upper()}_t<{n.upper()}_reg_{subtype}t>",
                'name': name,
                'args': [data['offset']]
            })
        env.Jinja2(of, '../templates/periph_instances.h.j2', headers = headers, instances = instances, aliases = aliases)
    return isources


sources.extend(template("nxp_uart", "uart.h", periph, "kxv1"))
sources.extend(template("stm32_uart", "uart.h", periph))
sources.extend(template("x16550_uart", "uart.h", periph))

Return('sources')